config/routes.rb
Rails.application.routes.draw do
  root 'report#index'

  resources :report, only: [:index]
  get 'report/filter', to: 'report#filter'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/report.rb
class Report < ApplicationRecord
  scope :filter_by_date, ->(start_date, end_date) { where(date: start_date..end_date) }
  scope :filter_by_fields, -> { Report.all }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/report_controller.rb
class ReportController < ApplicationController
  before_action :all_fields, only: [:index]
  before_action :dates, only: [:filter]
  before_action :fields, only: [:filter]

  def index
    @reports = Report.all
  end

  def filter
    @reports = @start_date.present? ? filter_with_date : filter_only_fields
    render 'report/index'
  rescue StandardError => e
    puts "Something went wrong with the filters => #{e}"
    redirect_to report_index_url
  end

  private

  def dates
    @start_date = params[:start_date] rescue ''
    @end_date = params[:end_date] rescue ''
  end

  def fields
    @fields = params[:fields].keys rescue all_fields
  end

  def filter_with_date
    Report.filter_by_date(@start_date, @end_date)
  end

  def filter_only_fields
    Report.filter_by_fields
  end

  def without_cpm
    params[:fields].keys - ['cpm']
  end

  def all_fields
    @fields = %w[connection app platform country cpm date]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/report_helper.rb
module ReportHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.css">
    <title>ReportsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'datatable', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
  <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.js"></script>
</html>

app/views/report/index.html.erb
<div class='body col-md-12'>
  <h1> Hello to the reports page </h1>

  <h3>The last reports are below:</h3>
  <hr>
  <div class="filters">
    <h4> Filters </h4>
    <%= render "report/shared/filters" %>
  </div>
  <hr>
  <div class="reportr">
    <%= render "report/shared/tables" %>
  </div>
</div

app/views/report/shared/_filters.html.erb
<%= form_tag report_filter_url, method: :get do %>
<div class='row'>
  <div class="filter_dates col-md-2">
    <div class="form-group">
      <%= label_tag 'Start Date' %>
        <%= text_field_tag :start_date, "", class: 'form-control col-md-12',
        'data-provide' => 'datepicker', 'data-date-format' => "dd/mm/yyyy" , placeholder: 'dd/mm/yyyy' %>
    </div>
    <div class="form-group">
      <%= label_tag 'Start Date' %>
        <%= text_field_tag :end_date, "", class: 'form-control col-md-12',
        'data-provide' => 'datepicker', 'data-date-format' => "dd/mm/yyyy" , placeholder: 'dd/mm/yyyy' %>
    </div>
  </div>

  <div class="filter_fields offset-md-1">
  <h4>Fields</h4>
    <div class="form-group">
      <%= check_box_tag "fields[connection]", nil, true %>
      <%= label_tag 'Connection' %>

      <%= check_box_tag "fields[app]", nil, true %>
      <%= label_tag 'App' %>

      <%= check_box_tag "fields[platform]", nil, true %>
      <%= label_tag 'Platform' %>
  </div>
    <div class="form-group">
      <%= check_box_tag "fields[country]", nil, true %>
      <%= label_tag 'Country' %>

      <%= check_box_tag "fields[cpm]", nil, true %>
      <%= label_tag 'CPM' %>

      <%= check_box_tag "fields[date]", nil, true, hidden: true%>

    </div>

  </div>
  </div>
  <%= submit_tag 'Filter', class: 'btn btn-primary' %>
    <% end %>

app/views/report/shared/_tables.html.erb
<table id='report_table' class="report_table table table-hover">
  <thead class='thead-light'>
    <tr>
      <% @fields.each do |field| %>
        <th>
          <%= field.capitalize %>
        </th>
      <% end %>
    </tr>

  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <% @fields.map do |field| %>
          <td>
            <%= field.eql?('cpm') ? ::Application::Cpm.new.render(report) : report.send(field) %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/report/show.html.erb
<h1>Report#show</h1>
<p>Find me in app/views/report/show.html.erb</p>